### ISSUE TITLE
Can't build motion-game, ~/.rubymotion-android not found

### ISSUE THREAD

**Issue by glennfu** [HipByte/motion-game#10]
I just installed RubyMotion on a fresh machine yesterday. My console shows:

→ which motion
/usr/local/bin/motion

Trying to run `rake build:all` for motion-game shows:

```
sh: /Users/Glenn/.rubymotion-android/ndk/toolchains/llvm-3.5/prebuilt/darwin-x86_64/bin/clang++: No such file or directory
rake aborted!
Command failed with status (127): [/Users/Glenn/.rubymotion-android/ndk/toolc...]
```

My home folder doesn't have a .ruby* folder. Is there something I can do on my end to fix this?

**Comment by lrz** [comment]
`rake build:all` will build all platforms of motion-game including Android, and to do so you need to have installed a proper Android environment. You can refer to this guide: http://www.rubymotion.com/developers/guides/manuals/android/getting-started

If you just want to build motion-game for iOS you can use the `rake build:ios` task instead.

**Comment by glennfu** [comment]
Understood, thanks!

**Comment by bmichotte** [comment]
Since the commit https://github.com/HipByte/motion-game/commit/2c35df5ee0267800beeb3cdd7f1503603731c87e, you can also set `RUBYMOTION_ANDROID_NDK` and `RUBYMOTION_ANDROID_SDK` in your .zshrc/.bashrc/.whateverrc and it should work

**Comment by glennfu** [comment]
I had to do a couple more things:

1. Add `require 'date'` to the top of the .gemspec file
2. Point my Gemfile to gem 'motion-game', path: "~/path/to/motion-game"

Now the game builds, MG::Button still works, and `on_touch_move` and `on_touch_end` are defined. However, they don't seem be called. I'm setting them up just like `on_touch_begin`, which works fine, in my Scene's initialize method, and added 'puts' statements to all of them. `on_touch_begin` works, `on_touch_move` and `on_touch_end` never get triggered. I'll keep investigating. Thanks for your help so far!

**Comment by lrz** [comment]
Can you paste the code somewhere? Would be interested to look into it and try reproducing the issue!

**Comment by glennfu** [comment]
Here's how I just reproduced it:

I checked out motion-game master branch, did `rake build:ios`, added `require 'date'` to .gemspec

Made a new game: `motion create --template=motion-game HelloWorld`

Change Gemfile to:
```
source 'https://rubygems.org'
gem 'rake'
gem 'motion-game', path: "~/path/to/motion-game"
```

`bundle install`

Added to MainScene#initialize:

```
    on_touch_begin do |touch|
      puts "touch: #{touch.location.x}, #{touch.location.y}"
    end
    
    on_touch_move do |touch, arg2|
      puts "touch moved: #{touch}, #{arg2}"
    end

    on_touch_end do |touch, arg2|
      puts "touch end: #{touch}, #{arg2}"
    end
```

Then I start tapping and dragging around on the screen and I only ever see the touch begin events.

**Comment by bmichotte** [comment]
`on_touch_*` can only have 0 or 1 args (`touch`), don't know if this change something btw

**Comment by glennfu** [comment]
I actually put some `std::cout` statements littered throughout the source and couldn't manage to get it to print out at that level either. I tried with both 0 and 1 args there and it didn't help.

**Comment by glennfu** [comment]
Also worth noting now, the MG::Button DOES indeed get all of begin/end/cancel/move events.

**Comment by glennfu** [comment]
UGH! I feel dumb. The answer is to `return true` at the end of on_touch_began. Any other return value stops further touch events for that tap. Spending more time in the cocos2d docs helped me find that.

**Comment by lrz** [comment]
Oh, now that makes sense! I wonder if there is something we could improve here. At the very least we should make sure to properly document this in the API reference!
