### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by accounts-at-softwarecriollo** [HipByte/motion-game#13]
Running rake ios:simulator on a new template app get:

`    Build build/ios/iPhoneSimulator-7.0-Development
     Build /Users/hugorincon/.rvm/gems/ruby-2.2.0/gems/motion-game-1.1/lib/motion-game/../../build/ios
      Link build/ios/iPhoneSimulator-7.0-Development/urbanz.app/urbanz
Undefined symbols for architecture i386:
  "_rb_vm_call_s", referenced from:
      mc_Application::applicationDidFinishLaunching() in libmotion-cocos.a(application.cpp.o)
      mc_Scene::update(float) in libmotion-cocos.a(layer.cpp.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [/Applications/Xcode.app/Contents/Developer...]
/Library/RubyMotion/lib/motion/project/builder.rb:357:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Library/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/ios.rb:186:in `block in <top (required)>'
`

Any idea?

**Comment by hugoerg56** [comment]
Same here @Watson1978 @MarkVillacampa ?

**Comment by Watson1978** [comment]
Which RubyMotion version  do you use?
Could you confirm the version with `motion --version` command.

motion-game need RubyMotion 4.7+.

**Comment by hugoerg56** [comment]
@Watson1978 I update to 4.9 and now get this:

`Undefined symbols for architecture i386:
  "_ruby_block_copy", referenced from:
      _ruby_block_descriptor_value in intro_scene.rb.o
      _ruby_block_descriptor_value in menu_scene.rb.o
      _ruby_block_descriptor_value in application.rb.o
  "_ruby_block_dispose", referenced from:
      _ruby_block_descriptor_value in intro_scene.rb.o
      _ruby_block_descriptor_value in menu_scene.rb.o
      _ruby_block_descriptor_value in application.rb.o
  "_vm_NSObject_ivar_dict", referenced from:
      _MREP_29CB74281FD345EF81EAF23C9AE69F91 in intro_scene.rb.o
      _MREP_17B7933F489349D99EE7430CA90B18FB in menu_scene.rb.o
      _MREP_A0C506A3E7D34B3B9D662CE44F8EEC97 in application.rb.o
  "_vm_char_to_rval", referenced from:
      ___unnamed_25 in intro_scene.rb.o
      ___unnamed_123 in menu_scene.rb.o
      ___unnamed_38 in application.rb.o
  "_vm_charptr_to_rval", referenced from:
      ___unnamed_64 in intro_scene.rb.o
      ___unnamed_162 in menu_scene.rb.o
      ___unnamed_77 in application.rb.o
  "_vm_dispatch", referenced from:
      _rb_scope__initialize__ in menu_scene.rb.o
      _rb_scope__add_label__ in menu_scene.rb.o
      _rb_scope__add_menu_option__ in menu_scene.rb.o
      _rb_scope__add_menu_option__block__ in menu_scene.rb.o
      _rb_scope__start__ in application.rb.o
     (maybe you meant: _rb_vm_dispatch, _rb_vm_dispatch_once_predicate )
  "_vm_double_to_rval", referenced from:
      ___unnamed_58 in intro_scene.rb.o
      ___unnamed_156 in menu_scene.rb.o
      ___unnamed_71 in application.rb.o
  "_vm_fast_div", referenced from:
      _rb_scope__add_label__ in menu_scene.rb.o
      _rb_scope__add_menu_option__ in menu_scene.rb.o
  "_vm_fast_minus", referenced from:
      _rb_scope__add_label__ in menu_scene.rb.o
      _rb_scope__add_menu_option__ in menu_scene.rb.o
  "_vm_fast_mult", referenced from:
      _rb_scope__add_menu_option__ in menu_scene.rb.o
  "_vm_float_to_rval", referenced from:
      ___unnamed_55 in intro_scene.rb.o
      ___unnamed_76 in menu_scene.rb.o
      ___unnamed_93 in menu_scene.rb.o
      ___unnamed_102 in menu_scene.rb.o
      ___unnamed_101 in menu_scene.rb.o
      ___unnamed_100 in menu_scene.rb.o
      ___unnamed_106 in menu_scene.rb.o
      ...
  "_vm_get_const", referenced from:
      _rb_scope1 in intro_scene.rb.o
      _rb_scope1 in menu_scene.rb.o
      _rb_scope__add_label__ in menu_scene.rb.o
      _rb_scope__add_menu_option__ in menu_scene.rb.o
      _rb_scope__add_menu_option__block__ in menu_scene.rb.o
      _rb_scope1 in application.rb.o
      _rb_scope__start__ in application.rb.o
      ...
     (maybe you meant: _rb_vm_get_constant_cache)
  "_vm_int_to_rval", referenced from:
      ___unnamed_37 in intro_scene.rb.o
      ___unnamed_135 in menu_scene.rb.o
      ___unnamed_50 in application.rb.o
  "_vm_long_long_to_rval", referenced from:
      ___unnamed_49 in intro_scene.rb.o
      ___unnamed_147 in menu_scene.rb.o
      ___unnamed_62 in application.rb.o
  "_vm_long_to_rval", referenced from:
      ___unnamed_43 in intro_scene.rb.o
      ___unnamed_141 in menu_scene.rb.o
      ___unnamed_56 in application.rb.o
  "_vm_name_to_sel", referenced from:
      _MREP_29CB74281FD345EF81EAF23C9AE69F91 in intro_scene.rb.o
      _MREP_17B7933F489349D99EE7430CA90B18FB in menu_scene.rb.o
      _MREP_A0C506A3E7D34B3B9D662CE44F8EEC97 in application.rb.o
  "_vm_ocval_to_rval", referenced from:
      ___unnamed_22 in intro_scene.rb.o
      ___unnamed_89 in menu_scene.rb.o
      ___unnamed_120 in menu_scene.rb.o
      ___unnamed_31 in application.rb.o
      ___unnamed_35 in application.rb.o
  "_vm_rary_new", referenced from:
      _rb_scope__add_label__ in menu_scene.rb.o
      _rb_scope__add_menu_option__ in menu_scene.rb.o
  "_vm_returned_from_block", referenced from:
      _rb_scope__add_menu_option__ in menu_scene.rb.o
     (maybe you meant: _rb_vm_returned_from_block)
  "_vm_rval_to_bool", referenced from:
      ___unnamed_60 in intro_scene.rb.o
      ___unnamed_158 in menu_scene.rb.o
      ___unnamed_73 in application.rb.o
  "_vm_rval_to_char", referenced from:
      ___unnamed_24 in intro_scene.rb.o
      ___unnamed_122 in menu_scene.rb.o
      ___unnamed_37 in application.rb.o
  "_vm_rval_to_charptr", referenced from:
      ___unnamed_63 in intro_scene.rb.o
      ___unnamed_161 in menu_scene.rb.o
      ___unnamed_76 in application.rb.o
  "_vm_rval_to_double", referenced from:
      ___unnamed_57 in intro_scene.rb.o
      ___unnamed_155 in menu_scene.rb.o
      ___unnamed_70 in application.rb.o
  "_vm_rval_to_float", referenced from:
      ___unnamed_54 in intro_scene.rb.o
      ___unnamed_83 in menu_scene.rb.o
      ___unnamed_86 in menu_scene.rb.o
      ___unnamed_102 in menu_scene.rb.o
      ___unnamed_101 in menu_scene.rb.o
      ___unnamed_100 in menu_scene.rb.o
      ___unnamed_106 in menu_scene.rb.o
      ...
  "_vm_rval_to_int", referenced from:
      ___unnamed_36 in intro_scene.rb.o
      ___unnamed_134 in menu_scene.rb.o
      ___unnamed_49 in application.rb.o
  "_vm_rval_to_long", referenced from:
      ___unnamed_42 in intro_scene.rb.o
      ___unnamed_140 in menu_scene.rb.o
      ___unnamed_55 in application.rb.o
  "_vm_rval_to_long_long", referenced from:
      ___unnamed_48 in intro_scene.rb.o
      ___unnamed_146 in menu_scene.rb.o
      ___unnamed_61 in application.rb.o
  "_vm_rval_to_ocval", referenced from:
      ___unnamed_9 in intro_scene.rb.o
      ___unnamed_21 in intro_scene.rb.o
      ___unnamed_9 in menu_scene.rb.o
      ___unnamed_16 in menu_scene.rb.o
      ___unnamed_19 in menu_scene.rb.o
      ___unnamed_78 in menu_scene.rb.o
      ___unnamed_80 in menu_scene.rb.o
      ...
  "_vm_rval_to_short", referenced from:
      ___unnamed_30 in intro_scene.rb.o
      ___unnamed_128 in menu_scene.rb.o
      ___unnamed_43 in application.rb.o
  "_vm_rval_to_uchar", referenced from:
      ___unnamed_27 in intro_scene.rb.o
      ___unnamed_125 in menu_scene.rb.o
      ___unnamed_40 in application.rb.o
  "_vm_rval_to_uint", referenced from:
      ___unnamed_39 in intro_scene.rb.o
      ___unnamed_137 in menu_scene.rb.o
      ___unnamed_52 in application.rb.o
  "_vm_rval_to_ulong", referenced from:
      ___unnamed_45 in intro_scene.rb.o
      ___unnamed_143 in menu_scene.rb.o
      ___unnamed_58 in application.rb.o
  "_vm_rval_to_ulong_long", referenced from:
      ___unnamed_51 in intro_scene.rb.o
      ___unnamed_149 in menu_scene.rb.o
      ___unnamed_64 in application.rb.o
  "_vm_rval_to_ushort", referenced from:
      ___unnamed_33 in intro_scene.rb.o
      ___unnamed_131 in menu_scene.rb.o
      ___unnamed_46 in application.rb.o
  "_vm_set_current_scope", referenced from:
      _rb_scope1 in intro_scene.rb.o
      _rb_scope1 in menu_scene.rb.o
      _rb_scope1 in application.rb.o
  "_vm_short_to_rval", referenced from:
      ___unnamed_31 in intro_scene.rb.o
      ___unnamed_129 in menu_scene.rb.o
      ___unnamed_44 in application.rb.o
  "_vm_uchar_to_rval", referenced from:
      ___unnamed_28 in intro_scene.rb.o
      ___unnamed_126 in menu_scene.rb.o
      ___unnamed_41 in application.rb.o
  "_vm_uint_to_rval", referenced from:
      ___unnamed_40 in intro_scene.rb.o
      ___unnamed_91 in menu_scene.rb.o
      ___unnamed_138 in menu_scene.rb.o
      ___unnamed_53 in application.rb.o
  "_vm_ulong_long_to_rval", referenced from:
      ___unnamed_52 in intro_scene.rb.o
      ___unnamed_150 in menu_scene.rb.o
      ___unnamed_65 in application.rb.o
  "_vm_ulong_to_rval", referenced from:
      ___unnamed_46 in intro_scene.rb.o
      ___unnamed_144 in menu_scene.rb.o
      ___unnamed_59 in application.rb.o
  "_vm_ushort_to_rval", referenced from:
      ___unnamed_34 in intro_scene.rb.o
      ___unnamed_132 in menu_scene.rb.o
      ___unnamed_47 in application.rb.o
ld: symbol(s) not found for architecture i386`

**Comment by Watson1978** [comment]
Please run `rake clean:all` at first after updated/downgraded RubyMotion.
New version generates binary which does not compatible with old version.

**Comment by hugoerg56** [comment]
Works like a charm. Thanks!
