### ISSUE TITLE
'ft2build.h' file not found creating a build 

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-game#16]
Doing:

$ git clone https://github.com/HipByte/motion-game.git
$ cd motion-game.git
$ rake build:ios

```
In file included from 2d/CCFontFreeType.cpp:26:
./2d/CCFontFreeType.h:34:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^
1 error generated.
rake aborted!
```

brew install freetype
Warning: freetype-2.6.3 already installed

Same issue, any idea? and thanks!

**Comment by Watson1978** [comment]
You don't need to install freetype.
Instead, you need to run "rake build:setup" following README

**Comment by hugoerg56** [comment]
@Watson1978 Thank you so much, it works perfectly creating the build locally. :+1:
