### ISSUE TITLE
Running portrait I see black spaces on top and bottom

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-game#18]
ex:
[http://take.ms/DsLGq](http://take.ms/DsLGq)

How I can use the full screen? Thanks!

**Comment by jjaffeux** [comment]
Do you have the three Default files in your resources folder ?

For example see : https://github.com/HipByte/RubyMotionSamples/tree/master/ios/Beers/resources

**Comment by hugoerg56** [comment]
@jjaffeux that was the problem, solved! thanks
