### ISSUE TITLE
MG::Scroll start on the bottom

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-game#30]
Creating a vertical scroll, the scroll content go to the bottom on init, this not should stay on the top?

**Comment by hugoerg56** [comment]
any idea? @MarkVillacampa @Watson1978 @lrz

**Comment by MarkVillacampa** [comment]
Can you share a small piece of code so we can reproduce this issue? Thanks!

**Comment by Watson1978** [comment]
I added some jump methods.
If you will call `Scroll#jump_to_bottom` method, you can start to scroll the view from bottom.
