### ISSUE TITLE
Unable to include files outside app folder

### ISSUE THREAD

**Issue by patrick-gleeson** [HipByte/motion-game#32]
Again, I'm probably being stupid. But doing a direct comparison between a vanilla RubyMotion app and a MotionGame app, I can successfully do this in the former:

```
app.files = Dir.glob('./app/**/*.rb') | Dir.glob('./../monkeys/**/*.rb')
```

And then in my code I can call `Monkeys::Bonobo.new`

Using MotionGame if I do that I get `uninitialized constant MainScene::Monkeys` even if I specify `app.files_dependencies 'app/main_scene.rb' => '../monkeys/bonobo.rb'` in my Rakefile. That specification works, which shows RubyMotion knows that bonobo.rb exists, but it still won't recognise the Monkeys module that I have defined in that file.

**Comment by Watson1978** [comment]
The files in`motion-game` has been contained in `app.files`.

Even If I added the following configuration in `config/ios.rb`, this problem could not be reproduced.
```
  app.files = app.files | Dir.glob('./../monkeys/**/*.rb')
```
