### ISSUE TITLE
Incorrect documentation for color option

### ISSUE THREAD

**Issue by andrewhavens** [HipByte/motion-game#34]
I was trying to figure out how to draw a circle. The `Draw` documentation says that the `dot` instance method accepts a `Color` as an an argument ([link](http://www.rubymotion.com/developers/motion-game/MG/Draw.html#dot-instance_method)). The `Color` documentation says that a symbol (like `:red`) or three value array (like `[0.2, 0.3, 0.4]`) can be passed as a color option. I could not get either of these to work.

> expected Array of 4 elements (ArgumentError)

I was able to get it to work with a four value array, where alpha was set to `1.0`. I'm not sure if this is a bug which does not allow these other short-cut options, or if this is an error in the documentation.

**Comment by eichert12** [comment]
It appears that the way color is dealt with is inconsistent (in both motion-game and Cocos2d-x).  Sometimes a 3 value array is expected, sometimes a 4 value array is expected.  We could update the places that expect a 4 value array to also accept a 3 value array and default the alpha.  For those that expect a 3 value array, we could either accept a 4 value array and ignore the alpha or raise an error.  Any thoughts on the best approach?  

Expects 3 value array
Node.color
Scene.color
Button.text_color
Layout.background_color

Expects 4 value array
Node.draw_rect/draw_dot/draw_triangle
Particle.start_color/end_color
Text.text_color
