### ISSUE TITLE
add Button#load_textures

### ISSUE THREAD

**Issue by amirrajan** [HipByte/motion-game#41]
```
void Button::loadTextures(const std::string& normal,
                          const std::string& selected,
                          const std::string& disabled,
                          TextureResType texType)
{
    loadTextureNormal(normal,texType);
    loadTexturePressed(selected,texType);
    loadTextureDisabled(disabled,texType);
}

```

Maybe set the default to `TextureResType textType` to `TextureResType::LOCAL:`?

**Comment by amirrajan** [comment]
This is pretty easy to do, for an example of how to do this, take a look at this pull request: https://github.com/HipByte/motion-game/pull/38

**Comment by amirrajan** [comment]
Can someone tag this as maybe something like "easy contribution"? It'll help people get involved if they want to try.

**Comment by Watson1978** [comment]
Fixed
