### ISSUE TITLE
Multi-resolution adaptation isn't supported

### ISSUE THREAD

**Issue by eichert12** [HipByte/motion-game#45]
With the current version of motion-game it isn't possible to implement the multi-resolution adaptation support that is available within Cocos-2d.

http://cocos2d-x.org/wiki/Detailed_explanation_of_Cocos2d-x_Multi-resolution_adaptation

Run the Flappy Bird sample with the iPhone 6 Plus as the device_name to see the issue that adding this support would address:
<img width="460" alt="screen shot 2016-08-29 at 8 05 02 am" src="https://cloud.githubusercontent.com/assets/4145/18050931/9171bec4-6dbf-11e6-9c8a-c972141c1630.png">

**Comment by hugoerg56** [comment]
I have a problem like that, Running the app on the simulator looks good, but in the real phne is smaller, any idea?

On the simulator:


![Image on simulator](http://community.rubymotion.com/uploads/default/original/1X/f52400741d47b92589ae502f647002c3e02c5a97.png)


![Image on real phone](http://community.rubymotion.com/uploads/default/original/1X/c4389a8c63ef5b401b280a7c168e827e94a4c617.png)

**Comment by hugoerg56** [comment]
@Watson1978 is the same app that I sent you by email, any idea?
