### ISSUE TITLE
App restart on background IOS

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-game#46]
1) I have the app running
2) I just press the home button
3) Go back to the app again

result: the app restart from the beginning.

Im getting this when the app go to background:

```
* thread #1: tid = 0xf8b5, 0x00000001916c9f08 libGPUSupportMercury.dylib`gpus_ReturnNotPermittedKillClient + 12, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1)
    frame #0: 0x00000001916c9f08 libGPUSupportMercury.dylib`gpus_ReturnNotPermittedKillClient + 12
libGPUSupportMercury.dylib`gpus_ReturnNotPermittedKillClient:
->  0x1916c9f08 <+12>: str    w9, [x8]
    0x1916c9f0c <+16>: ret    

libGPUSupportMercury.dylib`gpus_ReturnUnexpectedKillClient:
    0x1916c9f10 <+0>:  orr    w8, wzr, #0x1
    0x1916c9f14 <+4>:  str    w0, [x8]
```

Any idea? @Watson1978 @lrz @MarkVillacampa  I have a lot of app on rubymotion and that not happens.

**Comment by Watson1978** [comment]
Please attach reproduction code or your app.

**Comment by hugoerg56** [comment]
Hi Watson, I sent you the app to your email, thanks!

**Comment by Watson1978** [comment]
I think you have to stop animation when app will enter background.
http://stackoverflow.com/questions/29292868/lots-of-crashes-at-gpus-returnnotpermittedkillclient

The following is sample to start/stop Director and animation.

```ruby
class Application < MG::Application
  def start
 
    ...

    NSNotificationCenter.defaultCenter.addObserver(
      self,
      selector:"appWillResignActive:",
      name:UIApplicationWillResignActiveNotification,
      object:nil
    )
    NSNotificationCenter.defaultCenter.addObserver(
      self,
      selector:"appWillEnterForeground:",
      name:UIApplicationWillEnterForegroundNotification,
      object:nil
    )

    ...

  end

  def appWillEnterForeground(notification)
    NSLog("!!!!!! WillEnterForeground")
    MG::Director.shared.resume
    MG::Director.shared.start_animation
  end

  def appWillResignActive(notification)
    NSLog("!!!!!! WillResignActive")
    MG::Director.shared.pause
    MG::Director.shared.stop_animation
  end
```

**Comment by hugoerg56** [comment]
Awesome @Watson1978 that fixed the problem! thanks!

**Comment by eichert12** [comment]
@Watson1978 Does it make sense for Motion Game to do this vs. requiring everyone to implement the same logic?

**Comment by Watson1978** [comment]
@eichert12 I don't know everyone uses animation.

**Comment by eichert12** [comment]
@Watson1978 For a game I suspect the most common case will be some form of animation will be used.  It might not be running at the time the app is suspended though.....even so I think the most friendly way would be for motion-game to handle it.  Is there any harm in that being the default?  The alternate of requiring everyone to know about this and then implementing it themselves doesn't seem as nice.

**Comment by Watson1978** [comment]
@eichert12 It is better that motion-game has the logic in template or somewhere. But, I don't know everyone need the logic.

**Comment by eichert12** [comment]
@Watson1978 ok, I'll think about it a bit and if I come up with a suggestion for how to implement it I'll submit a pull request that we can discuss.

**Comment by Watson1978** [comment]
@hugoerg56 you can remove my workaround if you use latest commits
