### ISSUE TITLE
MG::Sprite.new should raise ArgumentError if no argument value was given

### ISSUE THREAD

**Issue by eichert12** [HipByte/motion-game#50]
On iOS MG::Sprite.new works fine and allows one to create a sprite which children that can be added to and then manipulated.  On Android this produced:

`Exception raised: ArgumentError: wrong number of arguments (0 for 1)`

The ability to have an empty Sprite and then build it up from children is useful and doing so on Android should work.

`@world = MG::Sprite.new # crashes on Android, works on iOS`

**Comment by Watson1978** [comment]
This is an issue in RubyMotion Android runtime.

I filed this in http://hipbyte.myjetbrains.com/youtrack/issue/RM-1116

**Comment by Watson1978** [comment]
`Sprite#new` has been defined with
```
rb_define_singleton_method(rb_cSprite, "new", sprite_new, 1);
```
This means that the method should take one argument.

So, `@world = MG::Sprite.new` raise `ArgumentError` with `wrong number of arguments (0 for 1)
`, this behavior is right.


> This is an issue in RubyMotion Android runtime.

wrong
This is problem in iOS platform

**Comment by eichert12** [comment]
Having a sprite that accepts no arguments is beneficial as you can then add children nodes such as Draw objects and use some of the features that are available on Sprite but not node.  I think having the ability to create a sprite without an image (i.e. No params) is something that should be supported.

**Comment by Watson1978** [comment]
When call `Sprite.new` on iOS, it just call `[[Sprite alloc] init]` in Objective-C because the number of arguments do not match.
In motion-game, it just define `new:` selector.

To solve this issue, we have to define `new` and then its method should call `new:`.

**Comment by Watson1978** [comment]
As easy way, `new` method allow variable argument.
```
    rb_define_singleton_method(klass, "new", new_instance, -1);
```
Even If call `new` without argument, `new_instance` function  will be called as expected.

Then receive each argument values using `rb_scan_args`
```
    rb_scan_args(argc, argv, "2", &delta_location, &interval);
```

If arguments number do not match, `rb_scan_args` will raise exception properly.
