### ISSUE TITLE
Can't use Flow with motion-game

### ISSUE THREAD

**Issue by eichert12** [HipByte/motion-game#52]
Given the way both gems implement invoke_rake the two gems can't be used together.  Being able to use Net and Store (in particular) would be useful from within motion-game.

**Comment by Watson1978** [comment]
Now, you can use Flow in motion-game app by https://github.com/HipByte/motion-game/commit/3e01e7deeae6a8a37d54f8dd533204f002153020

However, you should require Flow in Gemfile before motion-game so far, such as
```
source 'https://rubygems.org'

gem 'rake'
gem 'motion-flow' # Should require before 'motion-game'
gem 'motion-game'

# Add your dependencies for all platform here:
...
```
