### ISSUE TITLE
MG::Button inheritance

### ISSUE THREAD

**Issue by amirrajan** [HipByte/motion-game#53]
I have the following code for my main scene:

```ruby
class MainScene < MG::Scene
  def initialize
    sprite = Stone.new
    sprite.load_texture_normal("sprite.png")
    sprite.load_texture_pressed("sprite.png")
    sprite.position = [100, 100]
    sprite.scale = 1
    sprite.on_touch do |type|
    end

    add sprite
  end

  def update delta

  end
end
```

With `Stone` inheriting from `MG::Button`:

```ruby
class Stone < MG::Button
end
```

The setup above works correctly (the button is rendered with the correct sprite). But when I change the `Stone` class to set the `load_texture_normal` inside of the `initialize` method, it doesn't work:

```ruby
class MainScene < MG::Scene
  def initialize
    sprite = Stone.new
    sprite.position = [100, 100]
    sprite.scale = 1
    sprite.on_touch do |type|
    end

    add sprite
  end

  def update delta

  end
end
```

```ruby
class Stone < MG::Button
  def initalize
    super
    load_texture_normal("sprite.png")
    load_texture_pressed("sprite.png")
  end
end
```

**Comment by andrewhavens** [comment]
Ah, interesting. I think I noticed this same behavior when trying to subclass `MG::Sprite`.

**Comment by amirrajan** [comment]
Are we even supposed to do that, or should we just create factory methods maybe?

**Comment by amirrajan** [comment]
[This](http://discuss.cocos2d-x.org/t/subclass-button/21766/2) link does that. And there is this one off call to `CREATE_FUNC(ButtonSubClassName);`... not sure what that means.

**Comment by andrewhavens** [comment]
Seems like in anything RubyMotion, you should be able to subclass. I suppose it doesn't have to work that way. If not, then there needs be some kind of error raised to let the developer know that subclassing is not supported, rather than seeing unexpected results.

**Comment by amirrajan** [comment]
Based on [this](http://www.cocos2d-x.org/wiki/How_To_Subclass_Sprite_And_Add_Event_Listeners) Cocos2dx documentation, this seems to be the "recommended" approach:

```
class MainScene < MG::Scene
  def initialize
    sprite = Stone.create
    sprite.position = [100, 100]
    sprite.scale = 1
    sprite.on_touch do |type|
      puts "worky"
    end

    add sprite
  end

  def update delta

  end
end
```

```
class Stone < MG::Button
  def self.create
    sprite = Stone.new
    sprite.load_texture_normal("sprite.png")
    sprite.load_texture_pressed("sprite.png")
    sprite
  end
end
```
