### ISSUE TITLE
In Android nothing seems to be printed from C++

### ISSUE THREAD

**Issue by m3ltaw4y** [HipByte/motion-game#54]
Errors, logs, etc do not seem to cause any output to be displayed if the output is generated in the C++ portion of the project.  I am trying to debug a crashing C++ function but even 
cocos2d::log("Hello!");
Yields no output.  
If a crash occurs in a C++ function, nothing is displayed.

**Comment by Watson1978** [comment]
You can use `Kernel#p` or `Kernel#print` for printing log.

**Comment by m3ltaw4y** [comment]
I don't want to print from ruby.  I am trying to print from the C++ side.

**Comment by Watson1978** [comment]
If you want to use `cocos2d::log` in C++ code and it does not print anything, I think it is a problem in `cocos2d-x`.

**Comment by m3ltaw4y** [comment]
It isn't just logging.  NOTHING will be printed if there is a C++ crash.  I have added a method to sprite.cpp called create_with_image.  Now, I am sure it can be called and return a result.  However, within that function, absolutely nothing will be outputted.  If I have a bug in the function, this is how the program exits: 

(#<MainActivity:0x100ebe>)> MG::Sprite.create_with_image(imagename,imagesize)
--------- beginning of crash
Remote process has quit.
error: no devices found

**Comment by Watson1978** [comment]
You can confirm the log with `adb logcat` command if `cocos2d::log` works properly even if the log is not displayed in REPL.

```
$ .rubymotion-android/sdk/platform-tools/adb logcat
```

**Comment by m3ltaw4y** [comment]
Thanks!
