### ISSUE TITLE
How to set orientation

### ISSUE THREAD

**Issue by amirrajan** [HipByte/motion-game#6]
Random code snippet that took me a minute to figure out:

In `config/ios.rb`
```
Motion::Project::App.setup do |app|
  # Use `rake ios:config' to see complete project settings.
  app.info_plist['UISupportedInterfaceOrientations']  = ['UIInterfaceOrientationPortrait']
end
```

In previous apps I've done

```
  app.interface_orientations = [:portrait]
```

which didn't work for this project.

**Comment by jjaffeux** [comment]
I think this is related to this line :
https://github.com/HipByte/motion-game/blob/master/lib/motion-game/ios.rb#L13

I have slow internet atm I will check next week

**Comment by amirrajan** [comment]
I looked at the source and saw that too (which is how I figured out that's what you needed to use).

**Comment by lrz** [comment]
Maybe it didn't work because of the previously-set orientation in the default config file? (I assumed that by default MG projects should be in landscape, maybe I'm wrong here and we could remove this).

**Comment by amirrajan** [comment]
No, I think most people will want landscape to be the default.

**Comment by bmichotte** [comment]
btw, but, it's more a RubyMotion concern, I think, something like
```ruby
app.supported_orientations = [:landscape, :portrait]
```

Could be awesome to replace `app.info_plist['UISupportedInterfaceOrientations']` on iOS and 
```ruby
app.manifest.child('application').child('activity') do |main_activity|
    main_activity['android:screenOrientation'] = 'portrait'
  end
``` 
on Android

**Comment by hugoerg56** [comment]
in ios I just set:

```
Motion::Project::App.setup do |app|
  app.name = 'testapp'
  # valid values :portrait, :landscape_left, :landscape_right, :portrait_upside_down
  app.interface_orientations = [:landscape_left] 
end
```
