### ISSUE TITLE
[TODO] reject Symbol in loop count argument in Sprit#animate

### ISSUE THREAD

**Issue by Watson1978** [HipByte/motion-game#64]
I think this is not good design.

Because it does not handle negative value or non `:forever` symbol.

https://github.com/HipByte/motion-game/blob/3f3325964bb6baf78e1887ec00b5ae6f198d8a8c/src/sprite.cpp#L194-L199

I think it is better that it recognize with negative value as `:forever` mode and it is simple.

**Comment by andrewhavens** [comment]
You would rather pass -1 instead of `:forever`?

**Comment by andrewhavens** [comment]
Oh I see, you introduced `MG::Repeat::FOREVER`
