### ISSUE TITLE
Create new motion-game use wrong template files

### ISSUE THREAD

**Issue by casper91** [HipByte/motion-game#68]
When using `motion create --template=motion-game PROJECTNAME` it will use the template files from the oldest Gem version installed.

So I had to uninstall the older versions in order to use the new start template. 
Not sure if this is intended or a problem with how `motion` work.

**Comment by Watson1978** [comment]
Please remove older versions by `gem uninstall motion-game`.

I think this is a problem of RubyMotion build system in
https://github.com/HipByte/RubyMotion/blob/master/lib/motion/project/template.rb#L51-L58

**Comment by casper91** [comment]
Did that as well.

Filed it at:
http://community.rubymotion.com/t/motion-game-using-old-template-files/1951

Closing.
