### ISSUE TITLE
Using on_touch_end without on_touch_begin

### ISSUE THREAD

**Issue by casper91** [HipByte/motion-game#69]
I'm trying to do some simple Swipe detection. But it seems like I can't use `on_touch_end { |event| do_something }` without having defined `on_touch_begin` with something that returns `true` since `motion-game` is using `EventListenerTouchOneByOne` which requires something `true` returned in order  to not skip other registered events. 

I'm not sure if this is a bug or feature by `cocos2d` or `motion-game`. 
However I think you should be able to use `on_touch_end` without adding `on_touch_begin { |event| true }`, what do you think?

**Comment by Watson1978** [comment]
Looks like that `EventListenerTouchOneByOne` requires implementation of `onTouchBegan` event for other events by cocos2d-x design.

```
    // EventDispatcher will use the return value of 'onTouchBegan' to determine whether to pass following 'move', 'end'
    // message to 'EventListenerTouchOneByOne' or not. So 'onTouchBegan' needs to be set.
```

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/CCEventListenerTouch.cpp#L86-L87

**Comment by casper91** [comment]
Cool, thanks :)
