### ISSUE TITLE
Creating subclasses

### ISSUE THREAD

**Issue by prestia** [HipByte/motion-game#71]
I've been trying to create a subclass of `MG::Sprite` with no luck at all. The app crashes without any error message. Is this not supported?

I've included some streamlined code below.

**app/game_scene.rb**

    module MG
      class GameScene < Scene
        def initialize
          enemy = Enemy.new("enemy.png")
          enemy.position = [100,100]
            
          add enemy
        end
      end
    end

**app/enemy.rb**

    class Enemy < MG::Sprite
    end

**Comment by amirrajan** [comment]
This may be related: https://github.com/HipByte/motion-game/issues/53

**Comment by casper91** [comment]
It seems like after this [commit](https://github.com/HipByte/motion-game/commit/430e24059a15202d253cc150cd965664787777f3#diff-1e2e29f4912bbee028cd526455670b8bR1022) using constructor instead of singleton it is not possible to use with sub classes?
